import type { IntegrationCapability, IntegrationResourceType } from "./types.js";

export type ProviderCatalogEntry = {
  app: string;
  resourceType?: IntegrationResourceType;
  capabilities: IntegrationCapability[];
  normalizedSupport: "none" | "read_only" | "full";
  wave: "p0" | "p1" | "p2";
  genericRequestPolicy?: "list_recent_first" | "search_first" | "needs_explicit_scope";
  genericRequestTarget?: string;
  note?: string;
};

export const PROVIDER_CATALOG: ProviderCatalogEntry[] = [
  { app: "gmail", resourceType: "message", capabilities: ["list", "search", "read", "reply", "create"], normalizedSupport: "full", wave: "p0", genericRequestPolicy: "list_recent_first", genericRequestTarget: "recent email inbox" },
  { app: "outlook", resourceType: "message", capabilities: ["list", "search", "read", "reply", "create"], normalizedSupport: "full", wave: "p0", genericRequestPolicy: "list_recent_first", genericRequestTarget: "recent email inbox" },
  { app: "slack", resourceType: "message", capabilities: ["list", "search", "read", "reply"], normalizedSupport: "full", wave: "p0", genericRequestPolicy: "needs_explicit_scope", genericRequestTarget: "specific channel or thread" },
  { app: "zendesk", resourceType: "message", capabilities: ["list", "read", "reply"], normalizedSupport: "full", wave: "p0", genericRequestPolicy: "list_recent_first", genericRequestTarget: "recent support conversations" },
  { app: "intercom", resourceType: "message", capabilities: ["list", "search", "read", "reply"], normalizedSupport: "full", wave: "p1", genericRequestPolicy: "list_recent_first", genericRequestTarget: "recent support conversations" },

  { app: "notion", resourceType: "document", capabilities: ["list", "search", "read", "create", "update"], normalizedSupport: "full", wave: "p0", genericRequestPolicy: "search_first", genericRequestTarget: "documents or pages by topic" },
  { app: "googledocs", resourceType: "document", capabilities: ["list", "search", "read", "create", "update"], normalizedSupport: "full", wave: "p0", genericRequestPolicy: "search_first", genericRequestTarget: "documents by title or topic" },
  { app: "confluence", resourceType: "document", capabilities: ["list", "search", "read", "create", "update"], normalizedSupport: "full", wave: "p0", genericRequestPolicy: "needs_explicit_scope", genericRequestTarget: "specific Confluence space and optional parent page context", note: "Composio exposes page create and update actions. The normalized layer can support them when callers provide explicit space and optional parent-page context through additionalInput." },
  { app: "coda", resourceType: "document", capabilities: ["list", "search", "read"], normalizedSupport: "read_only", wave: "p1", genericRequestPolicy: "search_first", genericRequestTarget: "docs or pages by title or topic", note: "The current Coda toolkit supports document and page reads, but page-scoped writes require additional doc/page context beyond the generic normalized write contract." },
  { app: "miro", resourceType: "document", capabilities: ["list", "search", "read"], normalizedSupport: "read_only", wave: "p2", genericRequestPolicy: "search_first", genericRequestTarget: "boards by name or project", note: "The current Miro toolkit cleanly supports board listing, query-based board discovery, and board reads. Board creation exists in the live toolkit but is intentionally excluded until the generic document write contract can carry team/project scope safely." },

  { app: "jira", resourceType: "ticket", capabilities: ["list", "search", "read", "create", "update", "comment"], normalizedSupport: "full", wave: "p0", genericRequestPolicy: "search_first", genericRequestTarget: "issues by project, key, or keyword" },
  { app: "linear", resourceType: "ticket", capabilities: ["list", "read", "create", "update", "comment"], normalizedSupport: "full", wave: "p0", genericRequestPolicy: "list_recent_first", genericRequestTarget: "recent issues assigned to you or your team", note: "The current Linear toolkit exposes issue list/get/create/update/comment actions, but not a dedicated free-text issue search tool." },
  { app: "github", resourceType: "ticket", capabilities: ["list", "search", "read", "create", "update", "comment"], normalizedSupport: "full", wave: "p0", genericRequestPolicy: "list_recent_first", genericRequestTarget: "assigned issues and pull requests", note: "The current GitHub toolkit does not expose a personal notifications inbox. Generic GitHub requests should default to assigned issues and pull requests, and repository-scoped reads still require owner/repo context for detailed reads and writes." },
  { app: "asana", resourceType: "ticket", capabilities: ["list", "read", "comment"], normalizedSupport: "full", wave: "p1", genericRequestPolicy: "needs_explicit_scope", genericRequestTarget: "specific project or task context", note: "The current Asana toolkit supports task list/read/comment cleanly through the normalized layer. Task create and update require nested data payloads, so they are intentionally excluded for now." },
  { app: "clickup", resourceType: "ticket", capabilities: ["list", "read", "create", "update"], normalizedSupport: "full", wave: "p1", genericRequestPolicy: "needs_explicit_scope", genericRequestTarget: "specific workspace, team, or list context", note: "The current ClickUp toolkit supports list/read/create/update for tasks. Comment creation is omitted because the live toolkit requires extra reviewer-routing fields that do not fit the generic normalized comment contract." },
  { app: "trello", resourceType: "ticket", capabilities: ["list", "read", "create", "update", "comment"], normalizedSupport: "full", wave: "p1", genericRequestPolicy: "needs_explicit_scope", genericRequestTarget: "specific board or card context" },
  { app: "monday", resourceType: "ticket", capabilities: ["list", "create"], normalizedSupport: "full", wave: "p1", genericRequestPolicy: "needs_explicit_scope", genericRequestTarget: "specific board context", note: "The current Monday toolkit supports board-scoped item listing and creation. Item detail and normalized updates are omitted because the live toolkit lacks a clean single-item read/update action matching the generic ticket contract." },
  { app: "shortcut", resourceType: "ticket", capabilities: ["list", "search", "read", "create", "update", "comment"], normalizedSupport: "full", wave: "p2", genericRequestPolicy: "needs_explicit_scope", genericRequestTarget: "specific Shortcut project or story search", note: "The current Shortcut toolkit supports project-scoped story listing, search, read, create, update, and comment flows cleanly through the normalized ticket contract." },
  { app: "wrike", resourceType: "ticket", capabilities: ["list", "read", "create", "update"], normalizedSupport: "full", wave: "p2", genericRequestPolicy: "needs_explicit_scope", genericRequestTarget: "specific folder, space, or task context", note: "The current Wrike toolkit supports task list/read/create/update flows. Dedicated normalized search and comment actions are omitted because the live toolkit does not expose a clean generic ticket contract for them." },
  { app: "freshdesk", resourceType: "ticket", capabilities: ["list", "read", "create", "reply"], normalizedSupport: "full", wave: "p1", genericRequestPolicy: "list_recent_first", genericRequestTarget: "recent support tickets", note: "The current Freshdesk toolkit supports list/read/create/reply. Ticket update is omitted because the live update action requires additional type metadata beyond the generic normalized update contract." },
  { app: "sentry", resourceType: "ticket", capabilities: ["list", "search", "read"], normalizedSupport: "read_only", wave: "p2", genericRequestPolicy: "needs_explicit_scope", genericRequestTarget: "specific organization and project issue stream", note: "The current Sentry toolkit supports project issue listing, query-based filtering, and issue detail reads. Normalized support stays read-only because write flows require more provider-specific status routing than the generic ticket contract exposes." },

  { app: "googlecalendar", resourceType: "event", capabilities: ["list", "search", "read", "create", "update"], normalizedSupport: "full", wave: "p0", genericRequestPolicy: "list_recent_first", genericRequestTarget: "upcoming calendar events", note: "Normalized read is implemented as best-effort event lookup by event id, defaulting to the primary calendar when callers do not pass calendarId explicitly." },
  { app: "googlemeet", resourceType: "event", capabilities: ["list", "search", "read", "create", "update"], normalizedSupport: "full", wave: "p1", genericRequestPolicy: "needs_explicit_scope", genericRequestTarget: "specific meeting code, space name, or conference record context", note: "Normalized support covers meeting space create/read/update plus conference-record listing and lookup. Recordings and transcripts remain available in the raw toolkit but are not yet surfaced through the generic event contract." },
  { app: "zoom", resourceType: "event", capabilities: ["list", "read", "create", "update"], normalizedSupport: "full", wave: "p2", genericRequestPolicy: "needs_explicit_scope", genericRequestTarget: "specific Zoom user and meeting context", note: "The current Zoom toolkit supports user-scoped meeting listing, reads, creation, and updates. Generic search is omitted because the live toolkit does not expose a free-text meeting search action." },

  { app: "googledrive", resourceType: "file", capabilities: ["list", "search", "read", "create", "update"], normalizedSupport: "full", wave: "p0", genericRequestPolicy: "list_recent_first", genericRequestTarget: "recent files", note: "Composio exposes text-file create and edit actions. The normalized layer supports text-oriented file creation and updates; binary upload and richer permission/comment flows remain provider-specific." },
  { app: "dropbox", resourceType: "file", capabilities: ["list", "search", "read"], normalizedSupport: "read_only", wave: "p0", genericRequestPolicy: "list_recent_first", genericRequestTarget: "recent files" },
  { app: "box", resourceType: "file", capabilities: ["list", "search", "read"], normalizedSupport: "read_only", wave: "p2", genericRequestPolicy: "needs_explicit_scope", genericRequestTarget: "specific folder, file, or Box search query", note: "The current Box toolkit supports folder listing, content search, and file reads, but normalized support stays read-only." },

  { app: "hubspot", resourceType: "record", capabilities: ["list", "search", "read", "create", "update"], normalizedSupport: "full", wave: "p1", genericRequestPolicy: "search_first", genericRequestTarget: "contacts by name, email, or keyword", note: "The current HubSpot normalized path is centered on contacts. Reads work cleanly, while create and update rely on provider-specific contact fields passed through additionalInput." },
  { app: "salesforce", resourceType: "record", capabilities: ["list", "search", "read", "create", "update"], normalizedSupport: "full", wave: "p1", genericRequestPolicy: "search_first", genericRequestTarget: "contacts by name, account, or keyword", note: "The current Salesforce normalized path is centered on contact records." },
  { app: "linkedin", resourceType: "record", capabilities: ["list", "read", "create"], normalizedSupport: "full", wave: "p1", genericRequestPolicy: "needs_explicit_scope", genericRequestTarget: "your profile, managed company pages, or a post draft", note: "LinkedIn's current Composio toolkit supports profile info, managed company pages, and post creation. It does not expose job search or inbox/notification retrieval." },
  { app: "pipedrive", resourceType: "record", capabilities: ["list", "search", "read"], normalizedSupport: "read_only", wave: "p1", genericRequestPolicy: "search_first", genericRequestTarget: "people by name, organization, or keyword", note: "The current Pipedrive normalized path is centered on person records. Create and update are omitted because the live toolkit actions do not expose a stable generic field contract through the normalized layer." },

  { app: "googlesheets", resourceType: "spreadsheet", capabilities: ["list", "search", "create"], normalizedSupport: "full", wave: "p1", genericRequestPolicy: "search_first", genericRequestTarget: "spreadsheets or rows by title or lookup query", note: "The current Google Sheets toolkit supports spreadsheet search and append-style row creation, but it does not expose a clean normalized row read-by-id or generic row update action." },
  { app: "airtable", resourceType: "spreadsheet", capabilities: ["list", "read", "create", "update"], normalizedSupport: "full", wave: "p1", genericRequestPolicy: "needs_explicit_scope", genericRequestTarget: "specific base and table context", note: "Airtable normalized support is centered on record operations within an explicit base and table." },
];

export function getProviderCatalogEntry(app: string) {
  return PROVIDER_CATALOG.find((entry) => entry.app === app) ?? null;
}
